---
- name: include global default variables
  import_playbook: ../include_defaults.yml

- hosts: localhost
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: ../kubespray/roles/kubespray-defaults }
    - { role: ../kubespray/roles/container-engine }
    - { role: container-registry/client }
  tags: always

- import_playbook: ../kubespray/cluster.yml
  when: not exclude_k8s_images

- hosts: localhost
  tasks:
    - name: Download rook helm chart
      include_role:
        name: ceph/rook
      tags: download

    - name: Download decapod resources
      include_role:
        name: decapod
      tags: download

    - name: Download helm-repository resources
      include_role:
        name: helm-repository
      tags: download

- hosts: localhost
  name: download k8s clients
  roles:
    - { role: k8s/clients }
  vars:
    artifacts_dir: "{{ local_release_dir }}"
    install_k8s_clients: false

- hosts: localhost
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: ../kubespray/roles/kubespray-defaults }
    - { role: prepare-artifact }
    - { role: k8s/helm-repository }
  tags: always
