---
- name: set facts for prepare role
  set_fact:
    argo_version: "{{ argo_version }}"
    argo_workflow_controller_image_repo: "{{ argo_workflow_controller_image_repo }}"
    argo_workflow_executor_image_repo: "{{ argo_workflow_executor_image_repo }}"
    argo_server_image_repo: "{{ argo_server_image_repo }}"
    argo_mysql_image_repo: "{{ argo_mysql_image_repo }}"
    argo_mysql_version: "{{ argo_mysql_version }}"
    argocd_image_repo: "{{ argocd_image_repo }}"
    argocd_version: "{{ argocd_version }}"
    argocd_dex_image_repo: "{{ argocd_dex_image_repo }}"
    argocd_dex_version: "{{ argocd_dex_version }}"
    argocd_redis_image_repo: "{{ argocd_redis_image_repo }}"
    argocd_redis_version: "{{ argocd_redis_version }}"
  tags: download

- import_tasks: argo.yml
- import_tasks: argocd.yml

- name: check if decapod_flow directory exists
  stat:
    path: "{{ decapod_flow_dest }}"
  register: stat_decapod_flow_dest
  tags: download

- name: git clone decapod-flow
  git:
    repo: "{{ decapod_flow_source }}"
    dest: "{{ decapod_flow_dest }}"
    version: "{{ decapod_flow_version }}"
  when: not stat_decapod_flow_dest.stat.exists
  become: false
  tags: download

- name: install workflow templates and rbac
  shell: >-
    {{ bin_dir }}/kubectl apply -f {{ decapod_flow_dest }}/templates --recursive -nargo
  become: false

