name: Create diagram
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'
#  workflow_dispatch: {}
#  push:
#    branches:
#      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: git remote -v
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "repo_diagram.svg"
          excluded_paths: "ignore,.github"
 #         artifact_name: "repo-diagram"
 #     - name: Get artifact
 #       uses: actions/download-artifact@v2
 #       with:
 #         name: "repo-diagram"
 #         path: "downloads"
